# Generated by Django 4.2.7 on 2024-05-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPayment',
        ),
    ]
